# Generated by Django 4.1.4 on 2023-04-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image_portfolio',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
