# Generated by Django 4.1.4 on 2023-04-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_mypodcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypodcard',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
