# Generated by Django 4.1.4 on 2023-04-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
