# Generated by Django 4.1.4 on 2023-04-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
